### ISSUE TITLE
build setup

### ISSUE THREAD

**Issue by sjneph** [jhkorhonen/MOODS#9]
I noticed the layout of core/ relative to setup.py differs between the python zip download you provide and what you get with git clone.  I couldn't successfully build the git cloned version using build.sh or setup.py itself without first moving core/ into the python/ directory (where setup.py lives).  python/readme.MD, build.sh and setup.py made sense then.

**Comment by jhkorhonen** [comment]
See [Development](https://github.com/jhkorhonen/MOODS/wiki/Development) page on the wiki. The build instructions that come with sources assume that you downloaded the release `.tar.gz` linked on the github front page ([MOODS-python-1.9.2.tar.gz](https://github.com/jhkorhonen/MOODS/releases/download/v1.9.2/MOODS-python-1.9.2.tar.gz) currently). The Github "download zip" also gives the development tree instead of the release.
